name: teacher_app
description: "An app to instance iBeacons."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_beacon: ^0.5.1
  get: ^4.6.6
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  geolocator: ^13.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

flutter_native_splash:
  color: '#182026'
  image: assets/logos/splash_screen_logo.png

  android_12:
    color: '#182026'
    icon_background_color: '#182026'
    image: assets/logos/splash_screen_logo_big.png

  web: false
